import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>SamsWear - Wear the Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="text-red-500">Hey this is Samswear</div>

    </div>
  )
}
